sudo: required 
services:
   - docker
   
before_install:
   - docker build -t deepeshac280/docker-react -f Dockerfile.dev .
   
script: 
   - docker run deepeshac280/docker-react npm run test -- --coverage