version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    expose:
      - "3000"
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=production
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    command: ["npm", "run", "test"]